env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:functional/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - functional

rules: 
  import/extensions: 0
  import/no-unresolved: 0
  import/prefer-default-export: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  functional/no-return-void: 0
  functional/functional-parameters: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/no-throw-statements: 0
  functional/immutable-data: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  jsx-quotes: ['warn']
  quotes: ['warn']
  no-unused-vars: ['warn']
  semi: ['warn']
  comma-dangle: ['warn']